# Generated by Django 5.2.8 on 2025-11-12 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, message='Ответ не может быть пустым.')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, message='Вопрос не может быть пустым.')]),
        ),
    ]
